### ISSUE TITLE
Game crashes when using a Ticker Element to join a server

### ISSUE THREAD

**Issue by NextRaven10** [Keksuccino/FancyMenu#1055]
**Describe the bug**
When a Ticker element tries to run the Join Server function the game crashes. Meanwhile it works when a button uses it.

**To Reproduce**
1. Create a Ticker element that counts a variable up every few seconds. I have set it up so it counts up every second by one.
2. Create a second Ticker element that joins a server if the counting variable reaches a high number. For me it was 10, so basically 10 seconds after the game and the Main Screen are fully initiallized
3. Wait until the counting variable reaches your set number
4. See the game crash

**Expected behavior**
That the client would join the server the exact same way it does when you map the Join Server function to a button and press it.

**Game Log**
[Github Gist](https://gist.github.com/NextRaven10/a576d3c839cd6cd4b19ae02ed0324606)

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - FancyMenu Version 3.4.3_1.20.1
 - Drippy Version 3.0.11_1.20.1
 - Forge/Fabric Version 0.16.9
 - Minecraft Version 1.20.1
 - Active Mods: For me it was a lot. But I tried this without any mods other mods apart from the required ones and it still crashed

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.5.0!

**Comment by NextRaven10** [comment]
@Keksuccino This problem still exists on the 3.5.2 latest FancyMenu Version on. When I try to use a ticker to join a server or the last server / world it crashes instantly.
Here is the latest.log:

[latest.log](https://github.com/user-attachments/files/20233865/latest.log)
